plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    compileSdk 35

    defaultConfig {
        applicationId "com.playwire.demo_jetpack_compose"
        minSdk 24
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildTypes {
        debug {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion = "1.4.5"
    }
    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }

    flavorDimensions "distribution"
    productFlavors {
        total {
            dimension "distribution"
            applicationIdSuffix ".total"
            versionNameSuffix "-total"
        }
//        coppa {
//            dimension "distribution"
//            applicationIdSuffix ".coppa"
//            versionNameSuffix "-coppa"
//        }
    }
    namespace 'com.playwire.demo_jetpack_compose'
}

dependencies {

    implementation 'androidx.core:core-ktx:1.13.1'
    implementation "androidx.compose.ui:ui:$compose_version"
    implementation "androidx.compose.material:material:$compose_version"
    implementation "androidx.compose.ui:ui-tooling-preview:$compose_version"
    implementation "androidx.compose.runtime:runtime-livedata:$compose_version"
    implementation 'androidx.activity:activity-compose:1.9.2'
    implementation 'androidx.appcompat:appcompat:1.7.0'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
    androidTestImplementation "androidx.compose.ui:ui-test-junit4:$compose_version"
    debugImplementation "androidx.compose.ui:ui-tooling:$compose_version"
    debugImplementation "androidx.compose.ui:ui-test-manifest:$compose_version"


    implementation 'com.google.firebase:firebase-analytics-ktx:21.1.1'
    /// Total
    totalImplementation 'com.intergi.playwire:playwiresdk_total:10.6.1'
    /// COPPA
//    coppaImplementation 'com.intergi.playwire:playwiresdk_coppa:10.6.1'
}